### ISSUE TITLE
Filter for `volume > 0` removing valid quotes

### ISSUE THREAD

**Issue by marcotc** [cpankaj/yquotes#2]
Hello @cpankaj, thank you for the great work in this gem.

I was wondering what's the rationale behind filtering out quotes where trading `volume` is zero or less: https://github.com/cpankaj/yquotes/blob/079539175fada8979400966ff38606f9536997fc/lib/yquotes.rb#L56

My use case is related to this specific call:
`YQuotes::Client.new.get_quote('FFFHX', {:start_date=>"2017-05-30", :end_date=>"2017-05-31", :period=>"d"})`

Where Yahoo does return valid pricing, but with `volume: 0`. It seems like that specific security never reports their daily trading volume (always 0), so I can never get a valid historical pricing for it.

**Comment by cpankaj** [comment]
@marcotc Thanks for binging this to my attention.
For some historical data yahoo returns stock simulation data from weekends/holidays with volume = 0.
I have provided a way to fetch data without volume filter in the latest release.
`YQuotes::Client.new(false).get_quote('FFFHX', {:start_date=>"2017-05-30", :end_date=>"2017-05-31", :period=>"d"})`

Creating a client with **false** argument would allow you to fetch data without volume filter

**Comment by marcotc** [comment]
That's a great fix! Thank you so much! @cpankaj
